### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by toast12** [Wikinaut/agrep#7]
When I try to build on centos, I get this error:

checkfil.c:53: error: storage size of ‘buf’ isn’t known

Please suggest how to resolve this

**Comment by Wikinaut** [comment]
I can confirm this, looks to be a problem in the header definitions. Perhaps you can try an older version.

I will try to fix this compilation problem, but cannot fix it at the moment, sorry.

**Comment by toast12** [comment]
Is there a patch I can apply to resolve this error? I tried uncommenting include <sys/stat.h>, but get these errors:

In file included from checkfil.c:14:
/usr/include/sys/stat.h:442: error: redefinition of ‘stat’
/usr/include/sys/stat.h:435: error: previous definition of ‘stat’ was here

**Comment by con-mo8** [comment]
The above ^ fixes the build issues on OSX. There are still quite a few warnings under clang but no errors.

**Comment by Wikinaut** [comment]
fixed with https://github.com/Wikinaut/agrep/pull/11
